development:
  adapter: mysql2
  encoding: utf8
  database: web_app_experiment_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: web_app_experiment_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: web_app_experiment_production
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock